# Generated by Django 5.2.15 on 2026-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlog',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
